<<<<<<< HEAD
version: "3.9"

services:   
  app:
    build:
      context: .
      args:
       - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
=======
version: "3.9"

services:   
  app:
    build:
      context: .
      args:
       - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
>>>>>>> c2af00f3fe0ffb08e30b36700c6d791ef122017e
      sh -c "python manage.py runserver 0.0.0.0:8000"